image: node:16.14.2

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf dist
  - CI=false npm install

pages:
  stage: deploy
  script:
    - CI=false npm run build
    - rm -rf public
    - cp dist/index.html dist/404.html
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
